package com.jd.fms.finance.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Sep 10 13:33:29 CST 2013
 * Generated source version: 2.2.4
 * 
 */
 
@WebService(targetNamespace = "http://server.financialapp.fms.jd.com/", name = "FinancialSearchService")
@XmlSeeAlso({ObjectFactory.class})
public interface FinancialSearchService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFinancialOrderByOrderId", targetNamespace = "http://server.financialapp.fms.jd.com/", className = "com.jd.fms.finance.client.GetFinancialOrderByOrderId")
    @ResponseWrapper(localName = "getFinancialOrderByOrderIdResponse", targetNamespace = "http://server.financialapp.fms.jd.com/", className = "com.jd.fms.finance.client.GetFinancialOrderByOrderIdResponse")
    @WebMethod
    public long getFinancialOrderByOrderId(
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCaiWuMessageByOrderId", targetNamespace = "http://server.financialapp.fms.jd.com/", className = "com.jd.fms.finance.client.GetCaiWuMessageByOrderId")
    @ResponseWrapper(localName = "getCaiWuMessageByOrderIdResponse", targetNamespace = "http://server.financialapp.fms.jd.com/", className = "com.jd.fms.finance.client.GetCaiWuMessageByOrderIdResponse")
    @WebMethod
    public java.util.List<com.jd.fms.finance.client.GroupModel> getCaiWuMessageByOrderId(
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId
    );
}
