
/*
 * 
 */

package com.jd.fms.finance.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Sep 10 13:33:29 CST 2013
 * Generated source version: 2.2.4
 * 
 */


@WebServiceClient(name = "FinancialSearchServiceImplService", 
                  wsdlLocation = "http://isa.fm.360buy.com/ws/financialSearch?wsdl",
                  targetNamespace = "http://impl.server.financialapp.fms.jd.com/") 
public class FinancialSearchServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.server.financialapp.fms.jd.com/", "FinancialSearchServiceImplService");
    public final static QName FinancialSearchServiceImplPort = new QName("http://impl.server.financialapp.fms.jd.com/", "FinancialSearchServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://isa.fm.360buy.com/ws/financialSearch?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://isa.fm.360buy.com/ws/financialSearch?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public FinancialSearchServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FinancialSearchServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FinancialSearchServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns FinancialSearchService
     */
    @WebEndpoint(name = "FinancialSearchServiceImplPort")
    public FinancialSearchService getFinancialSearchServiceImplPort() {
        return super.getPort(FinancialSearchServiceImplPort, FinancialSearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FinancialSearchService
     */
    @WebEndpoint(name = "FinancialSearchServiceImplPort")
    public FinancialSearchService getFinancialSearchServiceImplPort(WebServiceFeature... features) {
        return super.getPort(FinancialSearchServiceImplPort, FinancialSearchService.class, features);
    }

}
