
/*
 * 
 */

package com.jd.bluedragon.distribution.send.ws.client.reverse;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Jul 05 10:53:21 CST 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "RevokeInfoWriteWebServiceService", 
                  wsdlLocation = "http://dmc.360buy.com/dmcrevoke/revokeInfoWriteService?wsdl",
                  targetNamespace = "http://service.webservice.revoke.dmc.jd.com/") 
public class RevokeInfoWriteWebServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.webservice.revoke.dmc.jd.com/", "RevokeInfoWriteWebServiceService");
    public final static QName RevokeInfoWriteWebServicePort = new QName("http://service.webservice.revoke.dmc.jd.com/", "RevokeInfoWriteWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://dmc.360buy.com/dmcrevoke/revokeInfoWriteService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://dmc.360buy.com/dmcrevoke/revokeInfoWriteService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public RevokeInfoWriteWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RevokeInfoWriteWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RevokeInfoWriteWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns RevokeInfoWriteWebService
     */
    @WebEndpoint(name = "RevokeInfoWriteWebServicePort")
    public RevokeInfoWriteWebService getRevokeInfoWriteWebServicePort() {
        return super.getPort(RevokeInfoWriteWebServicePort, RevokeInfoWriteWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RevokeInfoWriteWebService
     */
    @WebEndpoint(name = "RevokeInfoWriteWebServicePort")
    public RevokeInfoWriteWebService getRevokeInfoWriteWebServicePort(WebServiceFeature... features) {
        return super.getPort(RevokeInfoWriteWebServicePort, RevokeInfoWriteWebService.class, features);
    }

}
