package com.jd.bluedragon.distribution.send.ws.client.reverse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Jul 05 10:53:21 CST 2012
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://service.webservice.revoke.dmc.jd.com/", name = "RevokeInfoWriteWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface RevokeInfoWriteWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "syncOrderState", targetNamespace = "http://service.webservice.revoke.dmc.jd.com/", className = "com.jd.bluedragon.distribution.send.ws.client.reverse.SyncOrderState")
    @WebMethod
    @ResponseWrapper(localName = "syncOrderStateResponse", targetNamespace = "http://service.webservice.revoke.dmc.jd.com/", className = "com.jd.bluedragon.distribution.send.ws.client.reverse.SyncOrderStateResponse")
    public java.lang.String syncOrderState(
        @WebParam(name = "orderId", targetNamespace = "")
        java.lang.String orderId,
        @WebParam(name = "operatorName", targetNamespace = "")
        java.lang.String operatorName,
        @WebParam(name = "operateTime", targetNamespace = "")
        java.lang.String operateTime,
        @WebParam(name = "status", targetNamespace = "")
        int status
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendReturnDataToDMC", targetNamespace = "http://service.webservice.revoke.dmc.jd.com/", className = "com.jd.bluedragon.distribution.send.ws.client.reverse.SendReturnDataToDMC")
    @WebMethod
    @ResponseWrapper(localName = "sendReturnDataToDMCResponse", targetNamespace = "http://service.webservice.revoke.dmc.jd.com/", className = "com.jd.bluedragon.distribution.send.ws.client.reverse.SendReturnDataToDMCResponse")
    public java.lang.String sendReturnDataToDMC(
        @WebParam(name = "data", targetNamespace = "")
        java.lang.String data,
        @WebParam(name = "msgRoute", targetNamespace = "")
        java.lang.String msgRoute,
        @WebParam(name = "msgType", targetNamespace = "")
        int msgType,
        @WebParam(name = "sendTime", targetNamespace = "")
        java.lang.String sendTime,
        @WebParam(name = "rsn", targetNamespace = "")
        java.lang.String rsn
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getReturnDataByType", targetNamespace = "http://service.webservice.revoke.dmc.jd.com/", className = "com.jd.bluedragon.distribution.send.ws.client.reverse.GetReturnDataByType")
    @WebMethod
    @ResponseWrapper(localName = "getReturnDataByTypeResponse", targetNamespace = "http://service.webservice.revoke.dmc.jd.com/", className = "com.jd.bluedragon.distribution.send.ws.client.reverse.GetReturnDataByTypeResponse")
    public java.lang.String getReturnDataByType(
        @WebParam(name = "data", targetNamespace = "")
        java.lang.String data,
        @WebParam(name = "operateType", targetNamespace = "")
        java.lang.String operateType
    );
}
