package com.jd.wms.packExchange;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue May 21 15:52:41 GMT+08:00 2013
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://wms3.360buy.com", name = "BaseWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface BaseWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryWs", targetNamespace = "http://wms3.360buy.com", className = "com.jd.wms.packExchange.QueryWs")
    @WebMethod
    @ResponseWrapper(localName = "queryWsResponse", targetNamespace = "http://wms3.360buy.com", className = "com.jd.wms.packExchange.QueryWsResponse")
    public com.jd.wms.packExchange.Result queryWs(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processWs", targetNamespace = "http://wms3.360buy.com", className = "com.jd.wms.packExchange.ProcessWs")
    @WebMethod
    @ResponseWrapper(localName = "processWsResponse", targetNamespace = "http://wms3.360buy.com", className = "com.jd.wms.packExchange.ProcessWsResponse")
    public com.jd.wms.packExchange.Result processWs(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
