
/*
 * 
 */

package com.jd.wms.packExchange;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue May 21 15:52:41 GMT+08:00 2013
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "SimpleWebServiceSoap", 
                  wsdlLocation = "http://pex.ao1.360buy.net/services/packExchangeWebServiceSoap?wsdl",
                  targetNamespace = "http://wms3.360buy.com") 
public class SimpleWebServiceSoap extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://wms3.360buy.com", "SimpleWebServiceSoap");
    public final static QName SimpleWebServiceImplPort = new QName("http://wms3.360buy.com", "SimpleWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://pex.ao1.360buy.net/services/packExchangeWebServiceSoap?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://pex.ao1.360buy.net/services/packExchangeWebServiceSoap?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SimpleWebServiceSoap(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SimpleWebServiceSoap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleWebServiceSoap() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /**
     * 
     * @return
     *     returns BaseWebService
     */
    @WebEndpoint(name = "SimpleWebServiceImplPort")
    public BaseWebService getSimpleWebServiceImplPort() {
        return super.getPort(SimpleWebServiceImplPort, BaseWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaseWebService
     */
    @WebEndpoint(name = "SimpleWebServiceImplPort")
    public BaseWebService getSimpleWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SimpleWebServiceImplPort, BaseWebService.class, features);
    }

}
