package com.jd.bluedragon.distribution.send.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Mon Feb 27 17:07:34 CST 2012
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://tempuri.org/", name = "TuihuoServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TuihuoServiceSoap {

    @WebResult(name = "PutMessageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PutMessage", targetNamespace = "http://tempuri.org/", className = "com.jd.bluedragon.distribution.send.ws.client.PutMessage")
    @WebMethod(operationName = "PutMessage", action = "http://tempuri.org/PutMessage")
    @ResponseWrapper(localName = "PutMessageResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.bluedragon.distribution.send.ws.client.PutMessageResponse")
    public boolean putMessage(
        @WebParam(name = "orderId", targetNamespace = "http://tempuri.org/")
        int orderId,
        @WebParam(name = "zdid", targetNamespace = "http://tempuri.org/")
        int zdid,
        @WebParam(name = "operatorId", targetNamespace = "http://tempuri.org/")
        int operatorId,
        @WebParam(name = "operatorName", targetNamespace = "http://tempuri.org/")
        java.lang.String operatorName,
        @WebParam(name = "cky2", targetNamespace = "http://tempuri.org/")
        int cky2,
        @WebParam(name = "ob", targetNamespace = "http://tempuri.org/")
        java.lang.Object ob
    );

    @WebResult(name = "PutMessageByNewStoreIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PutMessageByNewStoreID", targetNamespace = "http://tempuri.org/", className = "com.jd.bluedragon.distribution.send.ws.client.PutMessageByNewStoreID")
    @WebMethod(operationName = "PutMessageByNewStoreID", action = "http://tempuri.org/PutMessageByNewStoreID")
    @ResponseWrapper(localName = "PutMessageByNewStoreIDResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.bluedragon.distribution.send.ws.client.PutMessageByNewStoreIDResponse")
    public com.jd.bluedragon.distribution.send.ws.client.ReturnMessage putMessageByNewStoreID(
        @WebParam(name = "model", targetNamespace = "http://tempuri.org/")
        com.jd.bluedragon.distribution.send.ws.client.Parameter model
    );
}
