
/*
 * 
 */

package com.jd.bluedragon.distribution.send.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Mon Feb 27 17:07:34 CST 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "TuihuoService", 
                  wsdlLocation = "http://10.10.224.79/TuihuoService.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
@Deprecated
public class TuihuoService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://tempuri.org/", "TuihuoService");
    public final static QName TuihuoServiceSoap12 = new QName("http://tempuri.org/", "TuihuoServiceSoap12");
    public final static QName TuihuoServiceSoap = new QName("http://tempuri.org/", "TuihuoServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://10.10.224.79/TuihuoService.asmx?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://10.10.224.79/TuihuoService.asmx?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public TuihuoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TuihuoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    public TuihuoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return returns TuihuoServiceSoap
     */
    @WebEndpoint(name = "TuihuoServiceSoap")
    public TuihuoServiceSoap getTuihuoServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/",
                "TuihuoServiceSoap"), TuihuoServiceSoap.class);
    }

    /**
     * 
     * @return returns TuihuoServiceSoap
     */
    @WebEndpoint(name = "TuihuoServiceSoap12")
    public TuihuoServiceSoap getTuihuoServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/",
                "TuihuoServiceSoap12"), TuihuoServiceSoap.class);
    }
}
