
package com.jd.bluedragon.distribution.send.domain.whems;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Aug 14 14:05:46 CST 2013
 * Generated source version: 2.3.1
 * 
 */

public final class Ems4JingDongPortType_Ems4JingDongHttpEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://jingdong.ws.whpost.cn", "ems4JingDong");

    private Ems4JingDongPortType_Ems4JingDongHttpEndpoint_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Ems4JingDong.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Ems4JingDong ss = new Ems4JingDong(wsdlURL, SERVICE_NAME);
        Ems4JingDongPortType port = ss.getEms4JingDongHttpEndpoint();  
        
        {
        System.out.println("Invoking sendMsg...");
        java.lang.String _sendMsg_content = "";
        java.lang.String _sendMsg__return = port.sendMsg(_sendMsg_content);
        System.out.println("sendMsg.result=" + _sendMsg__return);


        }

        System.exit(0);
    }

}
