
package com.jd.bluedragon.distribution.send.domain.whems;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Aug 14 14:05:46 CST 2013
 * Generated source version: 2.3.1
 * 
 */
 
public class Ems4JingDongPortType_Ems4JingDongHttpSoap11Endpoint_Server{

    protected Ems4JingDongPortType_Ems4JingDongHttpSoap11Endpoint_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new Ems4JingDongPortTypeImpl2();
        String address = "http://59.175.182.126/wh_ems/services/ems4JingDong.ems4JingDongHttpSoap11Endpoint/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new Ems4JingDongPortType_Ems4JingDongHttpSoap11Endpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
