
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.jd.bluedragon.distribution.send.domain.whems;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Aug 14 14:05:46 CST 2013
 * Generated source version: 2.3.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ems4JingDong",
                      portName = "ems4JingDongHttpSoap11Endpoint",
                      targetNamespace = "http://jingdong.ws.whpost.cn",
                      wsdlLocation = "http://59.175.182.126/wh_ems/services/ems4JingDong?wsdl",
                      endpointInterface = "com.Ems4JingDongPortType")
                      
public class Ems4JingDongPortTypeImpl implements Ems4JingDongPortType {

    private static final Logger LOG = Logger.getLogger(Ems4JingDongPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.Ems4JingDongPortType#sendMsg(java.lang.String  content )*
     */
    public java.lang.String sendMsg(java.lang.String content) { 
        LOG.info("Executing operation sendMsg");
        System.out.println(content);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
