package com.jd.bluedragon.distribution.send.domain.whems;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Aug 14 14:05:46 CST 2013
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://jingdong.ws.whpost.cn", name = "ems4JingDongPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface Ems4JingDongPortType {

    @WebResult(name = "return", targetNamespace = "http://jingdong.ws.whpost.cn")
    @Action(input = "urn:sendMsg", output = "urn:sendMsgResponse")
    @RequestWrapper(localName = "sendMsg", targetNamespace = "http://jingdong.ws.whpost.cn", className = "com.SendMsg")
    @WebMethod(action = "urn:sendMsg")
    @ResponseWrapper(localName = "sendMsgResponse", targetNamespace = "http://jingdong.ws.whpost.cn", className = "com.SendMsgResponse")
    public java.lang.String sendMsg(
        @WebParam(name = "content", targetNamespace = "http://jingdong.ws.whpost.cn")
        java.lang.String content
    );
}
