package com.jd.bluedragon.dbrouter;

public enum DynamicDataSourceType {
    DEFAULT,CONFIGCENTER,FAILSHIFT,FACTORMISS,CLL0814,HELING0603,XIANGLIAOBANK,XIANLIAO1229,ZHIWEILAI,
    CJBANK,CLOSEDBATE,AIYUEBA20180309,PGYU6ATQP5DBU;
}
