package com.jd.postal;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-11-27T10:31:49.373+08:00
 * Generated source version: 2.7.6
 * 
 */
public final class GetPrintDatasPortType_GetPrintDatasHttpEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://printService.webservice.bigaccount.hollycrm.com", "getPrintDatas");

    private GetPrintDatasPortType_GetPrintDatasHttpEndpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GetPrintDatas.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetPrintDatas ss = new GetPrintDatas(wsdlURL, SERVICE_NAME);
        GetPrintDatasPortType port = ss.getGetPrintDatasHttpEndpoint();  
        
        {
        System.out.println("Invoking printEMSDatas...");
        java.lang.String _printEMSDatas_xmlStr = "";
        java.lang.String _printEMSDatas__return = port.printEMSDatas(_printEMSDatas_xmlStr);
        System.out.println("printEMSDatas.result=" + _printEMSDatas__return);


        }
        {
        System.out.println("Invoking updatePrintEMSWeigth...");
        java.lang.String _updatePrintEMSWeigth_xmlStr = "";
        java.lang.String _updatePrintEMSWeigth__return = port.updatePrintEMSWeigth(_updatePrintEMSWeigth_xmlStr);
        System.out.println("updatePrintEMSWeigth.result=" + _updatePrintEMSWeigth__return);


        }
        {
        System.out.println("Invoking getBillNoByDs...");
        java.lang.String _getBillNoByDs_xmlStr = "";
        java.lang.String _getBillNoByDs__return = port.getBillNoByDs(_getBillNoByDs_xmlStr);
        System.out.println("getBillNoByDs.result=" + _getBillNoByDs__return);


        }
        {
        System.out.println("Invoking qryEMSDatasByCon...");
        java.lang.String _qryEMSDatasByCon_xmlStr = "";
        java.lang.String _qryEMSDatasByCon__return = port.qryEMSDatasByCon(_qryEMSDatasByCon_xmlStr);
        System.out.println("qryEMSDatasByCon.result=" + _qryEMSDatasByCon__return);


        }
        {
        System.out.println("Invoking getBillNoBySys...");
        java.lang.String _getBillNoBySys_xmlStr = "";
        java.lang.String _getBillNoBySys__return = port.getBillNoBySys(_getBillNoBySys_xmlStr);
        System.out.println("getBillNoBySys.result=" + _getBillNoBySys__return);


        }
        {
        System.out.println("Invoking updatePrintEMSDatas...");
        java.lang.String _updatePrintEMSDatas_xmlStr = "";
        java.lang.String _updatePrintEMSDatas__return = port.updatePrintEMSDatas(_updatePrintEMSDatas_xmlStr);
        System.out.println("updatePrintEMSDatas.result=" + _updatePrintEMSDatas__return);


        }
        {
        System.out.println("Invoking testWsOk...");
        java.lang.String _testWsOk_xmlStr = "";
        java.lang.String _testWsOk__return = port.testWsOk(_testWsOk_xmlStr);
        System.out.println("testWsOk.result=" + _testWsOk__return);


        }
        {
        System.out.println("Invoking updInterPrintDatas...");
        java.lang.String _updInterPrintDatas_xmlStr = "";
        java.lang.String _updInterPrintDatas__return = port.updInterPrintDatas(_updInterPrintDatas_xmlStr);
        System.out.println("updInterPrintDatas.result=" + _updInterPrintDatas__return);


        }
        {
        System.out.println("Invoking getBillNo...");
        java.lang.String _getBillNo_xmlStr = "";
        java.lang.String _getBillNo__return = port.getBillNo(_getBillNo_xmlStr);
        System.out.println("getBillNo.result=" + _getBillNo__return);


        }
        {
        System.out.println("Invoking qryEMSDataById...");
        java.lang.String _qryEMSDataById_xmlStr = "";
        java.lang.String _qryEMSDataById__return = port.qryEMSDataById(_qryEMSDataById_xmlStr);
        System.out.println("qryEMSDataById.result=" + _qryEMSDataById__return);


        }

        System.exit(0);
    }

}
