package com.jd.postal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-11-27T10:31:49.484+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", name = "getPrintDatasPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface GetPrintDatasPortType {

    @WebResult(name = "return", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
    @Action(input = "urn:printEMSDatas", output = "urn:printEMSDatasResponse")
    @RequestWrapper(localName = "printEMSDatas", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.PrintEMSDatas")
    @WebMethod(action = "urn:printEMSDatas")
    @ResponseWrapper(localName = "printEMSDatasResponse", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.PrintEMSDatasResponse")
    public java.lang.String printEMSDatas(
        @WebParam(name = "xmlStr", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
        java.lang.String xmlStr
    );

    @WebResult(name = "return", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
    @Action(input = "urn:updatePrintEMSWeigth", output = "urn:updatePrintEMSWeigthResponse")
    @RequestWrapper(localName = "updatePrintEMSWeigth", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.UpdatePrintEMSWeigth")
    @WebMethod(action = "urn:updatePrintEMSWeigth")
    @ResponseWrapper(localName = "updatePrintEMSWeigthResponse", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.UpdatePrintEMSWeigthResponse")
    public java.lang.String updatePrintEMSWeigth(
        @WebParam(name = "xmlStr", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
        java.lang.String xmlStr
    );

    @WebResult(name = "return", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
    @Action(input = "urn:getBillNoByDs", output = "urn:getBillNoByDsResponse")
    @RequestWrapper(localName = "getBillNoByDs", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.GetBillNoByDs")
    @WebMethod(action = "urn:getBillNoByDs")
    @ResponseWrapper(localName = "getBillNoByDsResponse", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.GetBillNoByDsResponse")
    public java.lang.String getBillNoByDs(
        @WebParam(name = "xmlStr", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
        java.lang.String xmlStr
    );

    @WebResult(name = "return", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
    @Action(input = "urn:qryEMSDatasByCon", output = "urn:qryEMSDatasByConResponse")
    @RequestWrapper(localName = "qryEMSDatasByCon", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.QryEMSDatasByCon")
    @WebMethod(action = "urn:qryEMSDatasByCon")
    @ResponseWrapper(localName = "qryEMSDatasByConResponse", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.QryEMSDatasByConResponse")
    public java.lang.String qryEMSDatasByCon(
        @WebParam(name = "xmlStr", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
        java.lang.String xmlStr
    );

    @WebResult(name = "return", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
    @Action(input = "urn:getBillNoBySys", output = "urn:getBillNoBySysResponse")
    @RequestWrapper(localName = "getBillNoBySys", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.GetBillNoBySys")
    @WebMethod(action = "urn:getBillNoBySys")
    @ResponseWrapper(localName = "getBillNoBySysResponse", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.GetBillNoBySysResponse")
    public java.lang.String getBillNoBySys(
        @WebParam(name = "xmlStr", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
        java.lang.String xmlStr
    );

    @WebResult(name = "return", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
    @Action(input = "urn:updatePrintEMSDatas", output = "urn:updatePrintEMSDatasResponse")
    @RequestWrapper(localName = "updatePrintEMSDatas", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.UpdatePrintEMSDatas")
    @WebMethod(action = "urn:updatePrintEMSDatas")
    @ResponseWrapper(localName = "updatePrintEMSDatasResponse", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.UpdatePrintEMSDatasResponse")
    public java.lang.String updatePrintEMSDatas(
        @WebParam(name = "xmlStr", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
        java.lang.String xmlStr
    );

    @WebResult(name = "return", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
    @Action(input = "urn:testWsOk", output = "urn:testWsOkResponse")
    @RequestWrapper(localName = "testWsOk", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.TestWsOk")
    @WebMethod(action = "urn:testWsOk")
    @ResponseWrapper(localName = "testWsOkResponse", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.TestWsOkResponse")
    public java.lang.String testWsOk(
        @WebParam(name = "xmlStr", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
        java.lang.String xmlStr
    );

    @WebResult(name = "return", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
    @Action(input = "urn:updInterPrintDatas", output = "urn:updInterPrintDatasResponse")
    @RequestWrapper(localName = "updInterPrintDatas", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.UpdInterPrintDatas")
    @WebMethod(action = "urn:updInterPrintDatas")
    @ResponseWrapper(localName = "updInterPrintDatasResponse", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.UpdInterPrintDatasResponse")
    public java.lang.String updInterPrintDatas(
        @WebParam(name = "xmlStr", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
        java.lang.String xmlStr
    );

    @WebResult(name = "return", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
    @Action(input = "urn:getBillNo", output = "urn:getBillNoResponse")
    @RequestWrapper(localName = "getBillNo", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.GetBillNo")
    @WebMethod(action = "urn:getBillNo")
    @ResponseWrapper(localName = "getBillNoResponse", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.GetBillNoResponse")
    public java.lang.String getBillNo(
        @WebParam(name = "xmlStr", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
        java.lang.String xmlStr
    );

    @WebResult(name = "return", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
    @Action(input = "urn:qryEMSDataById", output = "urn:qryEMSDataByIdResponse")
    @RequestWrapper(localName = "qryEMSDataById", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.QryEMSDataById")
    @WebMethod(action = "urn:qryEMSDataById")
    @ResponseWrapper(localName = "qryEMSDataByIdResponse", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com", className = "com.test.QryEMSDataByIdResponse")
    public java.lang.String qryEMSDataById(
        @WebParam(name = "xmlStr", targetNamespace = "http://printService.webservice.bigaccount.hollycrm.com")
        java.lang.String xmlStr
    );
}
