
/*
 * 
 */

package com.jd.bluedragon.distribution.send.ws.client.dmc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Fri Mar 30 11:57:14 CST 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "DmsToTmsWebServiceImplService", 
                  wsdlLocation = "http://10.10.224.176:8080/tms-dmc-web.war/services/dmsToTmsService?wsdl",
                  targetNamespace = "http://tms.360buy.com") 
public class DmsToTmsWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://tms.360buy.com", "DmsToTmsWebServiceImplService");
    public final static QName DmsToTmsWebServiceImplPort = new QName("http://tms.360buy.com", "DmsToTmsWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.10.224.176:8080/tms-dmc-web.war/services/dmsToTmsService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://10.10.224.176:8080/tms-dmc-web.war/services/dmsToTmsService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public DmsToTmsWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DmsToTmsWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DmsToTmsWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /**
     * 
     * @return
     *     returns DmsToTmsWebService
     */
    @WebEndpoint(name = "DmsToTmsWebServiceImplPort")
    public DmsToTmsWebService getDmsToTmsWebServiceImplPort() {
        return super.getPort(DmsToTmsWebServiceImplPort, DmsToTmsWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DmsToTmsWebService
     */
    @WebEndpoint(name = "DmsToTmsWebServiceImplPort")
    public DmsToTmsWebService getDmsToTmsWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DmsToTmsWebServiceImplPort, DmsToTmsWebService.class, features);
    }

}
