package com.jd.fa.orderrefund;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-06-05T13:37:05+08:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "RefundWebServiceImplService", 
                  wsdlLocation = "http://orderrefund.test.360buy.com/services/refundWebService?wsdl",
                  targetNamespace = "http://impl.server.webService.service.refundWonderful.jd.com/") 
public class RefundWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.server.webService.service.refundWonderful.jd.com/", "RefundWebServiceImplService");
    public final static QName RefundWebServiceImplPort = new QName("http://impl.server.webService.service.refundWonderful.jd.com/", "RefundWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://orderrefund.test.360buy.com/services/refundWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RefundWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://orderrefund.test.360buy.com/services/refundWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RefundWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RefundWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RefundWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns RefundWebService
     */
    @WebEndpoint(name = "RefundWebServiceImplPort")
    public RefundWebService getRefundWebServiceImplPort() {
        return super.getPort(RefundWebServiceImplPort, RefundWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RefundWebService
     */
    @WebEndpoint(name = "RefundWebServiceImplPort")
    public RefundWebService getRefundWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(RefundWebServiceImplPort, RefundWebService.class, features);
    }

}
