package com.jd.pop.sortcenter.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue Apr 23 14:39:35 CST 2013
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://offlineorder.service.order.pop.jd.com/", name = "SortCenterService")
@XmlSeeAlso({ObjectFactory.class})
public interface SortCenterService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchInfoForByOrderId", targetNamespace = "http://offlineorder.service.order.pop.jd.com/", className = "com.jd.pop.sortcenter.ws.SearchInfoForByOrderId")
    @WebMethod
    @ResponseWrapper(localName = "searchInfoForByOrderIdResponse", targetNamespace = "http://offlineorder.service.order.pop.jd.com/", className = "com.jd.pop.sortcenter.ws.SearchInfoForByOrderIdResponse")
    public com.jd.pop.sortcenter.ws.VenderOperInfoResult searchInfoForByOrderId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );
}
