
/*
 * 
 */

package com.jd.pop.sortcenter.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue Apr 23 14:39:35 CST 2013
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "SortCenterServiceImplService", 
                  wsdlLocation = "http://order.soa.pop.360buy.net/services/sortCenterService?wsdl",
                  targetNamespace = "http://impl.offlineorder.service.order.pop.jd.com/") 
public class SortCenterServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.offlineorder.service.order.pop.jd.com/", "SortCenterServiceImplService");
    public final static QName SortCenterServiceImplPort = new QName("http://impl.offlineorder.service.order.pop.jd.com/", "SortCenterServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://order.soa.pop.360buy.net/services/sortCenterService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://order.soa.pop.360buy.net/services/sortCenterService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SortCenterServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SortCenterServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SortCenterServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SortCenterServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }
    public SortCenterServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public SortCenterServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SortCenterService
     */
    @WebEndpoint(name = "SortCenterServiceImplPort")
    public SortCenterService getSortCenterServiceImplPort() {
        return super.getPort(SortCenterServiceImplPort, SortCenterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SortCenterService
     */
    @WebEndpoint(name = "SortCenterServiceImplPort")
    public SortCenterService getSortCenterServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SortCenterServiceImplPort, SortCenterService.class, features);
    }

}
