package com.jd.bluedragon.distribution.popAbnormal.ws.client.waybill;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Mon Dec 24 19:00:04 CST 2012
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://impl.rpc.waybill.etms.jd.com", name = "WaybillService")
@XmlSeeAlso({ObjectFactory.class})
public interface WaybillService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendWms3Packs", targetNamespace = "http://impl.rpc.waybill.etms.jd.com", className = "com.jd.bluedragon.distribution.popAbnormal.ws.client.waybill.SendWms3Packs")
    @WebMethod
    @ResponseWrapper(localName = "sendWms3PacksResponse", targetNamespace = "http://impl.rpc.waybill.etms.jd.com", className = "com.jd.bluedragon.distribution.popAbnormal.ws.client.waybill.SendWms3PacksResponse")
    public com.jd.bluedragon.distribution.popAbnormal.ws.client.waybill.BaseEntity sendWms3Packs(
        @WebParam(name = "jsonStr", targetNamespace = "")
        java.lang.String jsonStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendPopOrders", targetNamespace = "http://impl.rpc.waybill.etms.jd.com", className = "com.jd.bluedragon.distribution.popAbnormal.ws.client.waybill.SendPopOrders")
    @WebMethod
    @ResponseWrapper(localName = "sendPopOrdersResponse", targetNamespace = "http://impl.rpc.waybill.etms.jd.com", className = "com.jd.bluedragon.distribution.popAbnormal.ws.client.waybill.SendPopOrdersResponse")
    public com.jd.bluedragon.distribution.popAbnormal.ws.client.waybill.BaseEntity sendPopOrders(
        @WebParam(name = "popOrderDtoList", targetNamespace = "")
        java.util.List<com.jd.bluedragon.distribution.popAbnormal.ws.client.waybill.PopOrderDto> popOrderDtoList
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendOemPacks", targetNamespace = "http://impl.rpc.waybill.etms.jd.com", className = "com.jd.bluedragon.distribution.popAbnormal.ws.client.waybill.SendOemPacks")
    @WebMethod
    @ResponseWrapper(localName = "sendOemPacksResponse", targetNamespace = "http://impl.rpc.waybill.etms.jd.com", className = "com.jd.bluedragon.distribution.popAbnormal.ws.client.waybill.SendOemPacksResponse")
    public com.jd.bluedragon.distribution.popAbnormal.ws.client.waybill.BaseEntity sendOemPacks(
        @WebParam(name = "oemOrderDto", targetNamespace = "")
        com.jd.bluedragon.distribution.popAbnormal.ws.client.waybill.OemOrderDto oemOrderDto
    );
}
