/*
 *
 */

package com.jd.loss.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.3.1 Tue Feb 26 18:04:39 CST 2013
 * Generated source version: 2.3.1
 *
 */

@WebServiceClient(name = "BlueDragonWebServiceService", wsdlLocation = "http://loss.360buy.com/services/blueDragonWebService?wsdl", targetNamespace = "http://ws.ldms.pis.bk.jd.com/")
public class BlueDragonWebServiceService extends Service {

	public final static URL WSDL_LOCATION;
	public final static QName SERVICE = new QName("http://ws.ldms.pis.bk.jd.com/",
	        "BlueDragonWebServiceService");
	public final static QName BlueDragonWebServicePort = new QName("http://ws.ldms.pis.bk.jd.com/",
	        "BlueDragonWebServicePort");
	static {
		URL url = null;
		try {
			url = new URL("http://loss.360buy.com/services/blueDragonWebService?wsdl");
		} catch (MalformedURLException e) {
			System.err
			        .println("Can not initialize the default wsdl from http://loss.360buy.com/services/blueDragonWebService?wsdl");
			// e.printStackTrace();
		}
		WSDL_LOCATION = url;
	}

	public BlueDragonWebServiceService(URL wsdlLocation) {
		super(wsdlLocation, BlueDragonWebServiceService.SERVICE);
	}

	public BlueDragonWebServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public BlueDragonWebServiceService() {
		super(BlueDragonWebServiceService.WSDL_LOCATION, BlueDragonWebServiceService.SERVICE);
	}

	/**
	 *
	 * @return returns BlueDragonWebService
	 */
	@WebEndpoint(name = "BlueDragonWebServicePort")
	public BlueDragonWebService getBlueDragonWebServicePort() {
		return super.getPort(BlueDragonWebServiceService.BlueDragonWebServicePort,
		        BlueDragonWebService.class);
	}

	/**
	 *
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns BlueDragonWebService
	 */
	@WebEndpoint(name = "BlueDragonWebServicePort")
	public BlueDragonWebService getBlueDragonWebServicePort(WebServiceFeature... features) {
		return super.getPort(BlueDragonWebServiceService.BlueDragonWebServicePort,
		        BlueDragonWebService.class, features);
	}

}
