package com.jd.loss.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue Feb 26 18:04:39 CST 2013
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://ws.ldms.pis.bk.jd.com/", name = "BlueDragonWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface BlueDragonWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLossProductByOrderId", targetNamespace = "http://ws.ldms.pis.bk.jd.com/", className = "com.jd.loss.client.GetLossProductByOrderId")
    @WebMethod
    @ResponseWrapper(localName = "getLossProductByOrderIdResponse", targetNamespace = "http://ws.ldms.pis.bk.jd.com/", className = "com.jd.loss.client.GetLossProductByOrderIdResponse")
    public java.util.List<com.jd.loss.client.LossProduct> getLossProductByOrderId(
        @WebParam(name = "orderId", targetNamespace = "")
        java.lang.String orderId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLossProductCountOrderId", targetNamespace = "http://ws.ldms.pis.bk.jd.com/", className = "com.jd.loss.client.GetLossProductCountOrderId")
    @WebMethod
    @ResponseWrapper(localName = "getLossProductCountOrderIdResponse", targetNamespace = "http://ws.ldms.pis.bk.jd.com/", className = "com.jd.loss.client.GetLossProductCountOrderIdResponse")
    public int getLossProductCountOrderId(
        @WebParam(name = "orderId", targetNamespace = "")
        java.lang.String orderId
    );
}
