package com.jd.fa.refundService;
//
//import java.net.MalformedURLException;
//import java.net.URL;
//import javax.xml.namespace.QName;
//import javax.xml.ws.WebEndpoint;
//import javax.xml.ws.WebServiceClient;
//import javax.xml.ws.WebServiceFeature;
//import javax.xml.ws.Service;
//
///**
// * This class was generated by Apache CXF 2.5.1
// * 2013-06-07T17:43:57.901+08:00
// * Generated source version: 2.5.1
// * 
// */
//@WebServiceClient(name = "RefundService", 
//                  wsdlLocation = "http://financecd.360buy.com/Refund/Service/RefundService.asmx?WSDL",
//                  targetNamespace = "http://tempuri.org/") 
//public class RefundService extends Service {
//
//    public final static URL WSDL_LOCATION;
//
//    public final static QName SERVICE = new QName("http://tempuri.org/", "RefundService");
//    public final static QName RefundServiceSoap12 = new QName("http://tempuri.org/", "RefundServiceSoap12");
//    public final static QName RefundServiceSoap = new QName("http://tempuri.org/", "RefundServiceSoap");
//    static {
//        URL url = null;
//        try {
//            url = new URL("http://financecd.360buy.com/Refund/Service/RefundService.asmx?WSDL");
//        } catch (MalformedURLException e) {
//            java.util.logging.Logger.getLogger(RefundService.class.getName())
//                .log(java.util.logging.Level.INFO, 
//                     "Can not initialize the default wsdl from {0}", "http://financecd.360buy.com/Refund/Service/RefundService.asmx?WSDL");
//        }
//        WSDL_LOCATION = url;
//    }
//
//    public RefundService(URL wsdlLocation) {
//        super(wsdlLocation, SERVICE);
//    }
//
//    public RefundService(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }
//
//    public RefundService() {
//        super(WSDL_LOCATION, SERVICE);
//    }
//
//    /**
//     *
//     * @return
//     *     returns RefundServiceSoap
//     */
//    @WebEndpoint(name = "RefundServiceSoap12")
//    public RefundServiceSoap getRefundServiceSoap12() {
//        return super.getPort(RefundServiceSoap12, RefundServiceSoap.class);
//    }
//
//    /**
//     * 
//     * @param features
//     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return
//     *     returns RefundServiceSoap
//     */
//    @WebEndpoint(name = "RefundServiceSoap12")
//    public RefundServiceSoap getRefundServiceSoap12(WebServiceFeature... features) {
//        return super.getPort(RefundServiceSoap12, RefundServiceSoap.class, features);
//    }
//    /**
//     *
//     * @return
//     *     returns RefundServiceSoap
//     */
//    @WebEndpoint(name = "RefundServiceSoap")
//    public RefundServiceSoap getRefundServiceSoap() {
//        return super.getPort(RefundServiceSoap, RefundServiceSoap.class);
//    }
//
//    /**
//     * 
//     * @param features
//     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return
//     *     returns RefundServiceSoap
//     */
//    @WebEndpoint(name = "RefundServiceSoap")
//    public RefundServiceSoap getRefundServiceSoap(WebServiceFeature... features) {
//        return super.getPort(RefundServiceSoap, RefundServiceSoap.class, features);
//    }
//
//}
