package com.jd.fa.refundService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Sep 04 13:46:09 GMT+08:00 2013
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://tempuri.org/", name = "RefundServiceNewSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface RefundServiceNewSoap {

    @WebResult(name = "IsexistenceRefundResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsexistenceRefund", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.IsexistenceRefund")
    @WebMethod(operationName = "IsexistenceRefund", action = "http://tempuri.org/IsexistenceRefund")
    @ResponseWrapper(localName = "IsexistenceRefundResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.IsexistenceRefundResponse")
    public boolean isexistenceRefund(
        @WebParam(name = "orderid", targetNamespace = "http://tempuri.org/")
        long orderid
    );

    @WebResult(name = "IsExitRefundResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsExitRefund", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.IsExitRefund")
    @WebMethod(operationName = "IsExitRefund", action = "http://tempuri.org/IsExitRefund")
    @ResponseWrapper(localName = "IsExitRefundResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.IsExitRefundResponse")
    public boolean isExitRefund(
        @WebParam(name = "orderid", targetNamespace = "http://tempuri.org/")
        long orderid
    );

    @WebResult(name = "GetRecommandTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRecommandType", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetRecommandType")
    @WebMethod(operationName = "GetRecommandType", action = "http://tempuri.org/GetRecommandType")
    @ResponseWrapper(localName = "GetRecommandTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetRecommandTypeResponse")
    public com.jd.fa.refundService.ValidOrderTemp getRecommandType(
        @WebParam(name = "orderid", targetNamespace = "http://tempuri.org/")
        long orderid
    );

    @WebResult(name = "InnerSystemApplyForCheckWithTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InnerSystemApplyForCheckWithType", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.InnerSystemApplyForCheckWithType")
    @WebMethod(operationName = "InnerSystemApplyForCheckWithType", action = "http://tempuri.org/InnerSystemApplyForCheckWithType")
    @ResponseWrapper(localName = "InnerSystemApplyForCheckWithTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.InnerSystemApplyForCheckWithTypeResponse")
    public com.jd.fa.refundService.ValidRequest innerSystemApplyForCheckWithType(
        @WebParam(name = "requestParam", targetNamespace = "http://tempuri.org/")
        com.jd.fa.refundService.CustomerRequestNew requestParam,
        @WebParam(name = "businessType", targetNamespace = "http://tempuri.org/")
        int businessType
    );

    @WebResult(name = "CustomerApplyForCheckWithTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CustomerApplyForCheckWithType", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.CustomerApplyForCheckWithType")
    @WebMethod(operationName = "CustomerApplyForCheckWithType", action = "http://tempuri.org/CustomerApplyForCheckWithType")
    @ResponseWrapper(localName = "CustomerApplyForCheckWithTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.CustomerApplyForCheckWithTypeResponse")
    public com.jd.fa.refundService.ValidRequest customerApplyForCheckWithType(
        @WebParam(name = "requestParam", targetNamespace = "http://tempuri.org/")
        com.jd.fa.refundService.CustomerRequestNew requestParam
    );

    @WebResult(name = "GetRequestSheetsByOrderIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRequestSheetsByOrderId", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetRequestSheetsByOrderId")
    @WebMethod(operationName = "GetRequestSheetsByOrderId", action = "http://tempuri.org/GetRequestSheetsByOrderId")
    @ResponseWrapper(localName = "GetRequestSheetsByOrderIdResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetRequestSheetsByOrderIdResponse")
    public com.jd.fa.refundService.ArrayOfReqSheet getRequestSheetsByOrderId(
        @WebParam(name = "orderid", targetNamespace = "http://tempuri.org/")
        long orderid
    );

    @WebResult(name = "GetDisplayRefundTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDisplayRefundType", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetDisplayRefundType")
    @WebMethod(operationName = "GetDisplayRefundType", action = "http://tempuri.org/GetDisplayRefundType")
    @ResponseWrapper(localName = "GetDisplayRefundTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetDisplayRefundTypeResponse")
    public java.lang.String getDisplayRefundType(
        @WebParam(name = "orderid", targetNamespace = "http://tempuri.org/")
        long orderid
    );

    @WebResult(name = "SendXmlMessageWithObjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendXmlMessageWithObject", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.SendXmlMessageWithObject")
    @WebMethod(operationName = "SendXmlMessageWithObject", action = "http://tempuri.org/SendXmlMessageWithObject")
    @ResponseWrapper(localName = "SendXmlMessageWithObjectResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.SendXmlMessageWithObjectResponse")
    public java.lang.String sendXmlMessageWithObject(
        @WebParam(name = "rrd", targetNamespace = "http://tempuri.org/")
        com.jd.fa.refundService.RefundReceiptDetailNew rrd
    );

    @WebResult(name = "OrderRefundIsProcessingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OrderRefundIsProcessing", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.OrderRefundIsProcessing")
    @WebMethod(operationName = "OrderRefundIsProcessing", action = "http://tempuri.org/OrderRefundIsProcessing")
    @ResponseWrapper(localName = "OrderRefundIsProcessingResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.OrderRefundIsProcessingResponse")
    public boolean orderRefundIsProcessing(
        @WebParam(name = "orderid", targetNamespace = "http://tempuri.org/")
        long orderid
    );
}
