package com.jd.fa.refundService;
//
//import javax.jws.WebMethod;
//import javax.jws.WebParam;
//import javax.jws.WebResult;
//import javax.jws.WebService;
//import javax.xml.bind.annotation.XmlSeeAlso;
//import javax.xml.ws.RequestWrapper;
//import javax.xml.ws.ResponseWrapper;
//
///**
// * This class was generated by Apache CXF 2.5.1
// * 2013-06-07T17:43:57.846+08:00
// * Generated source version: 2.5.1
// * 
// */
//@WebService(targetNamespace = "http://tempuri.org/", name = "RefundServiceSoap")
//@XmlSeeAlso({ObjectFactory.class})
//public interface RefundServiceSoap {
//
//    /**
//     * <span style='color:blue'>[TicketRefundReceiptWebService]</span> 根据订单号获取到历史提交记录
//     */
//    @WebResult(name = "GetRefundListByOrderIdResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "GetRefundListByOrderId", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetRefundListByOrderId")
//    @WebMethod(operationName = "GetRefundListByOrderId", action = "http://tempuri.org/GetRefundListByOrderId")
//    @ResponseWrapper(localName = "GetRefundListByOrderIdResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetRefundListByOrderIdResponse")
//    public com.jd.fa.refundService.ArrayOfRefundModelForAfs getRefundListByOrderId(
//        @WebParam(name = "orderid", targetNamespace = "http://tempuri.org/")
//        java.lang.String orderid
//    );
//
//    /**
//     * <span style='color:blue'>[TicketRefundReceiptWebService]</span> 判断该订单是否已经申请退款
//     */
//    @WebResult(name = "IsexistenceRefundResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "IsexistenceRefund", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.IsexistenceRefund")
//    @WebMethod(operationName = "IsexistenceRefund", action = "http://tempuri.org/IsexistenceRefund")
//    @ResponseWrapper(localName = "IsexistenceRefundResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.IsexistenceRefundResponse")
//    public boolean isexistenceRefund(
//        @WebParam(name = "orderid", targetNamespace = "http://tempuri.org/")
//        int orderid
//    );
//
//    @WebResult(name = "IsExitRefundResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "IsExitRefund", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.IsExitRefund")
//    @WebMethod(operationName = "IsExitRefund", action = "http://tempuri.org/IsExitRefund")
//    @ResponseWrapper(localName = "IsExitRefundResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.IsExitRefundResponse")
//    public boolean isExitRefund(
//        @WebParam(name = "orderid", targetNamespace = "http://tempuri.org/")
//        int orderid
//    );
//
//    @WebResult(name = "RefundConfirmResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "RefundConfirm", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.RefundConfirm")
//    @WebMethod(operationName = "RefundConfirm", action = "http://tempuri.org/RefundConfirm")
//    @ResponseWrapper(localName = "RefundConfirmResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.RefundConfirmResponse")
//    public boolean refundConfirm(
//        @WebParam(name = "RefundResultXml", targetNamespace = "http://tempuri.org/")
//        java.lang.String refundResultXml
//    );
//
//    @WebResult(name = "SendXmlMessageResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "SendXmlMessage", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.SendXmlMessage")
//    @WebMethod(operationName = "SendXmlMessage", action = "http://tempuri.org/SendXmlMessage")
//    @ResponseWrapper(localName = "SendXmlMessageResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.SendXmlMessageResponse")
//    public java.lang.String sendXmlMessage(
//        @WebParam(name = "param", targetNamespace = "http://tempuri.org/")
//        com.jd.fa.refundService.XmlMessage param
//    );
//
//    @WebResult(name = "GetStateByConditionResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "GetStateByCondition", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetStateByCondition")
//    @WebMethod(operationName = "GetStateByCondition", action = "http://tempuri.org/GetStateByCondition")
//    @ResponseWrapper(localName = "GetStateByConditionResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetStateByConditionResponse")
//    public int getStateByCondition(
//        @WebParam(name = "param", targetNamespace = "http://tempuri.org/")
//        com.jd.fa.refundService.StateModel param
//    );
//
//    @WebResult(name = "GetRecommandTypeResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "GetRecommandType", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetRecommandType")
//    @WebMethod(operationName = "GetRecommandType", action = "http://tempuri.org/GetRecommandType")
//    @ResponseWrapper(localName = "GetRecommandTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetRecommandTypeResponse")
//    public com.jd.fa.refundService.ValidOrderTemp getRecommandType(
//        @WebParam(name = "orderid", targetNamespace = "http://tempuri.org/")
//        int orderid
//    );
//
//    /**
//     * <span style='color:blue'>[InnerSystemApplyForCheckWithType]</span> 接收内部系统退款申请的方法
//     */
//    @WebResult(name = "InnerSystemApplyForCheckWithTypeResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "InnerSystemApplyForCheckWithType", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.InnerSystemApplyForCheckWithType")
//    @WebMethod(operationName = "InnerSystemApplyForCheckWithType", action = "http://tempuri.org/InnerSystemApplyForCheckWithType")
//    @ResponseWrapper(localName = "InnerSystemApplyForCheckWithTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.InnerSystemApplyForCheckWithTypeResponse")
//    public com.jd.fa.refundService.ValidRequest innerSystemApplyForCheckWithType(
//        @WebParam(name = "requestParam", targetNamespace = "http://tempuri.org/")
//        com.jd.fa.refundService.CustomerRequest requestParam,
//        @WebParam(name = "businessType", targetNamespace = "http://tempuri.org/")
//        int businessType
//    );
//
//    @WebResult(name = "CustomerApplyForCheckWithTypeResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "CustomerApplyForCheckWithType", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.CustomerApplyForCheckWithType")
//    @WebMethod(operationName = "CustomerApplyForCheckWithType", action = "http://tempuri.org/CustomerApplyForCheckWithType")
//    @ResponseWrapper(localName = "CustomerApplyForCheckWithTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.CustomerApplyForCheckWithTypeResponse")
//    public com.jd.fa.refundService.ValidRequest customerApplyForCheckWithType(
//        @WebParam(name = "requestParam", targetNamespace = "http://tempuri.org/")
//        com.jd.fa.refundService.CustomerRequest requestParam
//    );
//
//    @WebResult(name = "GetRequestSheetsByOrderIdResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "GetRequestSheetsByOrderId", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetRequestSheetsByOrderId")
//    @WebMethod(operationName = "GetRequestSheetsByOrderId", action = "http://tempuri.org/GetRequestSheetsByOrderId")
//    @ResponseWrapper(localName = "GetRequestSheetsByOrderIdResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetRequestSheetsByOrderIdResponse")
//    public com.jd.fa.refundService.ArrayOfReqSheet getRequestSheetsByOrderId(
//        @WebParam(name = "orderid", targetNamespace = "http://tempuri.org/")
//        int orderid
//    );
//
//    /**
//     * <span style='color:blue'>[GetDisplayRefundType]</span> 查询订单可以申请的退款类型
//     */
//    @WebResult(name = "GetDisplayRefundTypeResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "GetDisplayRefundType", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetDisplayRefundType")
//    @WebMethod(operationName = "GetDisplayRefundType", action = "http://tempuri.org/GetDisplayRefundType")
//    @ResponseWrapper(localName = "GetDisplayRefundTypeResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.GetDisplayRefundTypeResponse")
//    public java.lang.String getDisplayRefundType(
//        @WebParam(name = "orderid", targetNamespace = "http://tempuri.org/")
//        int orderid
//    );
//
//    /**
//     * <span style='color:blue'>[TicketRefundReceiptWebService]</span> 驳回退款申请
//     */
//    @RequestWrapper(localName = "DisallowRefund", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.DisallowRefund")
//    @WebMethod(operationName = "DisallowRefund", action = "http://tempuri.org/DisallowRefund")
//    @ResponseWrapper(localName = "DisallowRefundResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.DisallowRefundResponse")
//    public void disallowRefund(
//        @WebParam(name = "requestid", targetNamespace = "http://tempuri.org/")
//        int requestid,
//        @WebParam(name = "CurrentUserName", targetNamespace = "http://tempuri.org/")
//        java.lang.String currentUserName,
//        @WebParam(mode = WebParam.Mode.OUT, name = "DisallowRefundResult", targetNamespace = "http://tempuri.org/")
//        javax.xml.ws.Holder<java.lang.Boolean> disallowRefundResult,
//        @WebParam(mode = WebParam.Mode.OUT, name = "outMessage", targetNamespace = "http://tempuri.org/")
//        javax.xml.ws.Holder<java.lang.String> outMessage
//    );
//
//    @WebResult(name = "SendXmlMessageWithObjectResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "SendXmlMessageWithObject", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.SendXmlMessageWithObject")
//    @WebMethod(operationName = "SendXmlMessageWithObject", action = "http://tempuri.org/SendXmlMessageWithObject")
//    @ResponseWrapper(localName = "SendXmlMessageWithObjectResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.SendXmlMessageWithObjectResponse")
//    public java.lang.String sendXmlMessageWithObject(
//        @WebParam(name = "rrd", targetNamespace = "http://tempuri.org/")
//        com.jd.fa.refundService.RefundReceiptDetail rrd
//    );
//
//    @WebResult(name = "PopRefundResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "PopRefund", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.PopRefund")
//    @WebMethod(operationName = "PopRefund", action = "http://tempuri.org/PopRefund")
//    @ResponseWrapper(localName = "PopRefundResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.PopRefundResponse")
//    public com.jd.fa.refundService.ValidRequest popRefund(
//        @WebParam(name = "requestParam", targetNamespace = "http://tempuri.org/")
//        com.jd.fa.refundService.PopRequest requestParam
//    );
//
//    /**
//     * <span style='color:blue'>[TicketRefundReceiptWebService]</span> 查询订单是否有正在处理中的退款申请
//     */
//    @WebResult(name = "OrderRefundIsProcessingResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "OrderRefundIsProcessing", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.OrderRefundIsProcessing")
//    @WebMethod(operationName = "OrderRefundIsProcessing", action = "http://tempuri.org/OrderRefundIsProcessing")
//    @ResponseWrapper(localName = "OrderRefundIsProcessingResponse", targetNamespace = "http://tempuri.org/", className = "com.jd.fa.refundService.OrderRefundIsProcessingResponse")
//    public boolean orderRefundIsProcessing(
//        @WebParam(name = "orderid", targetNamespace = "http://tempuri.org/")
//        int orderid
//    );
//}
