package com.jd.wms.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Nov 27 10:19:45 CST 2012
 * Generated source version: 2.2.4
 * 
 */
 
@WebService(targetNamespace = "http://interface-dtc-ws.360buy.com", name = "Inbound")
@XmlSeeAlso({ObjectFactory.class})
public interface Inbound {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "directHandleMessage", targetNamespace = "http://interface-dtc-ws.360buy.com", className = "com.jd.wms.ws.DirectHandleMessage")
    @ResponseWrapper(localName = "directHandleMessageResponse", targetNamespace = "http://interface-dtc-ws.360buy.com", className = "com.jd.wms.ws.DirectHandleMessageResponse")
    @WebMethod
    public com.jd.wms.ws.Result directHandleMessage(
        @WebParam(name = "target", targetNamespace = "")
        java.lang.String target,
        @WebParam(name = "methodName", targetNamespace = "")
        java.lang.String methodName,
        @WebParam(name = "messageValue", targetNamespace = "")
        java.lang.String messageValue,
        @WebParam(name = "outboundNo", targetNamespace = "")
        java.lang.String outboundNo,
        @WebParam(name = "outboundType", targetNamespace = "")
        java.lang.String outboundType,
        @WebParam(name = "source", targetNamespace = "")
        java.lang.String source
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "forwardHandleMessage", targetNamespace = "http://interface-dtc-ws.360buy.com", className = "com.jd.wms.ws.ForwardHandleMessage")
    @ResponseWrapper(localName = "forwardHandleMessageResponse", targetNamespace = "http://interface-dtc-ws.360buy.com", className = "com.jd.wms.ws.ForwardHandleMessageResponse")
    @WebMethod
    public com.jd.wms.ws.Result forwardHandleMessage(
        @WebParam(name = "target", targetNamespace = "")
        java.lang.String target,
        @WebParam(name = "methodName", targetNamespace = "")
        java.lang.String methodName,
        @WebParam(name = "messageValue", targetNamespace = "")
        java.lang.String messageValue,
        @WebParam(name = "outboundNo", targetNamespace = "")
        java.lang.String outboundNo,
        @WebParam(name = "outboundType", targetNamespace = "")
        java.lang.String outboundType,
        @WebParam(name = "source", targetNamespace = "")
        java.lang.String source
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "forwardSaveHandleMessage", targetNamespace = "http://interface-dtc-ws.360buy.com", className = "com.jd.wms.ws.ForwardSaveHandleMessage")
    @ResponseWrapper(localName = "forwardSaveHandleMessageResponse", targetNamespace = "http://interface-dtc-ws.360buy.com", className = "com.jd.wms.ws.ForwardSaveHandleMessageResponse")
    @WebMethod
    public com.jd.wms.ws.Result forwardSaveHandleMessage(
        @WebParam(name = "category", targetNamespace = "")
        java.lang.String category,
        @WebParam(name = "businessType", targetNamespace = "")
        java.lang.String businessType,
        @WebParam(name = "methodName", targetNamespace = "")
        java.lang.String methodName,
        @WebParam(name = "messageValue", targetNamespace = "")
        java.lang.String messageValue,
        @WebParam(name = "source", targetNamespace = "")
        java.lang.String source
    );
}
