
package com.jd.wms.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Nov 27 10:19:45 CST 2012
 * Generated source version: 2.2.4
 * 
 */

public final class Inbound_InboundImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://interface-dtc-ws.360buy.com", "InboundImplService");

    private Inbound_InboundImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = InboundImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        InboundImplService ss = new InboundImplService(wsdlURL, Inbound_InboundImplPort_Client.SERVICE_NAME);
        Inbound port = ss.getInboundImplPort();  
        
        {
        System.out.println("Invoking directHandleMessage...");
        java.lang.String _directHandleMessage_target = "";
        java.lang.String _directHandleMessage_methodName = "";
        java.lang.String _directHandleMessage_messageValue = "";
        java.lang.String _directHandleMessage_outboundNo = "";
        java.lang.String _directHandleMessage_outboundType = "";
        java.lang.String _directHandleMessage_source = "";
        com.jd.wms.ws.Result _directHandleMessage__return = port.directHandleMessage(_directHandleMessage_target, _directHandleMessage_methodName, _directHandleMessage_messageValue, _directHandleMessage_outboundNo, _directHandleMessage_outboundType, _directHandleMessage_source);
        System.out.println("directHandleMessage.result=" + _directHandleMessage__return);


        }
        {
        System.out.println("Invoking forwardHandleMessage...");
        java.lang.String _forwardHandleMessage_target = "";
        java.lang.String _forwardHandleMessage_methodName = "";
        java.lang.String _forwardHandleMessage_messageValue = "";
        java.lang.String _forwardHandleMessage_outboundNo = "";
        java.lang.String _forwardHandleMessage_outboundType = "";
        java.lang.String _forwardHandleMessage_source = "";
        com.jd.wms.ws.Result _forwardHandleMessage__return = port.forwardHandleMessage(_forwardHandleMessage_target, _forwardHandleMessage_methodName, _forwardHandleMessage_messageValue, _forwardHandleMessage_outboundNo, _forwardHandleMessage_outboundType, _forwardHandleMessage_source);
        System.out.println("forwardHandleMessage.result=" + _forwardHandleMessage__return);


        }
        {
        System.out.println("Invoking forwardSaveHandleMessage...");
        java.lang.String _forwardSaveHandleMessage_category = "";
        java.lang.String _forwardSaveHandleMessage_businessType = "";
        java.lang.String _forwardSaveHandleMessage_methodName = "";
        java.lang.String _forwardSaveHandleMessage_messageValue = "";
        java.lang.String _forwardSaveHandleMessage_source = "";
        com.jd.wms.ws.Result _forwardSaveHandleMessage__return = port.forwardSaveHandleMessage(_forwardSaveHandleMessage_category, _forwardSaveHandleMessage_businessType, _forwardSaveHandleMessage_methodName, _forwardSaveHandleMessage_messageValue, _forwardSaveHandleMessage_source);
        System.out.println("forwardSaveHandleMessage.result=" + _forwardSaveHandleMessage__return);


        }

        System.exit(0);
    }

}
