
/*
 * 
 */

package com.jd.iwmss.stock.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.4
 * Sun Sep 22 14:13:18 CST 2013
 * Generated source version: 2.2.4
 * 
 */


@WebServiceClient(name = "StockWebService", 
                  wsdlLocation = "http://iwmss.360buy.com/StockWebService.asmx?wsdl",
                  targetNamespace = "http://360buy.com/") 
public class StockWebService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://360buy.com/", "StockWebService");
    public final static QName StockWebServiceSoap12 = new QName("http://360buy.com/", "StockWebServiceSoap12");
    public final static QName StockWebServiceSoap = new QName("http://360buy.com/", "StockWebServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://iwmss.360buy.com/StockWebService.asmx?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://iwmss.360buy.com/StockWebService.asmx?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public StockWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StockWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockWebService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns StockWebServiceSoap
     */
    @WebEndpoint(name = "StockWebServiceSoap12")
    public StockWebServiceSoap getStockWebServiceSoap12() {
        return super.getPort(StockWebServiceSoap12, StockWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockWebServiceSoap
     */
    @WebEndpoint(name = "StockWebServiceSoap12")
    public StockWebServiceSoap getStockWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(StockWebServiceSoap12, StockWebServiceSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns StockWebServiceSoap
     */
    @WebEndpoint(name = "StockWebServiceSoap")
    public StockWebServiceSoap getStockWebServiceSoap() {
        return super.getPort(StockWebServiceSoap, StockWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockWebServiceSoap
     */
    @WebEndpoint(name = "StockWebServiceSoap")
    public StockWebServiceSoap getStockWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(StockWebServiceSoap, StockWebServiceSoap.class, features);
    }

}
