package com.jd.iwmss.stock.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.4
 * Sun Sep 22 14:13:18 CST 2013
 * Generated source version: 2.2.4
 * 
 */
 
@WebService(targetNamespace = "http://360buy.com/", name = "StockWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface StockWebServiceSoap {

    @WebResult(name = "GetStockByRemarkResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetStockByRemark", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockByRemark")
    @ResponseWrapper(localName = "GetStockByRemarkResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockByRemarkResponse")
    @WebMethod(operationName = "GetStockByRemark", action = "http://360buy.com/GetStockByRemark")
    public com.jd.iwmss.stock.client.Stock getStockByRemark(
        @WebParam(name = "remark", targetNamespace = "http://360buy.com/")
        java.lang.String remark
    );

    @WebResult(name = "GetStockDetailsByKdanhaosResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetStockDetailsByKdanhaos", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockDetailsByKdanhaos")
    @ResponseWrapper(localName = "GetStockDetailsByKdanhaosResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockDetailsByKdanhaosResponse")
    @WebMethod(operationName = "GetStockDetailsByKdanhaos", action = "http://360buy.com/GetStockDetailsByKdanhaos")
    public com.jd.iwmss.stock.client.ArrayOfStockDetail getStockDetailsByKdanhaos(
        @WebParam(name = "strKdanhao", targetNamespace = "http://360buy.com/")
        java.lang.String strKdanhao
    );

    @WebResult(name = "GetStocksResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetStocks", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStocks")
    @ResponseWrapper(localName = "GetStocksResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStocksResponse")
    @WebMethod(operationName = "GetStocks", action = "http://360buy.com/GetStocks")
    public com.jd.iwmss.stock.client.ArrayOfStock getStocks(
        @WebParam(name = "stock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.StockParamter stock
    );

    @WebResult(name = "InsertStockResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "InsertStock", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.InsertStock")
    @ResponseWrapper(localName = "InsertStockResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.InsertStockResponse")
    @WebMethod(operationName = "InsertStock", action = "http://360buy.com/InsertStock")
    public int insertStock(
        @WebParam(name = "stock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock stock
    );

    @WebResult(name = "GetRevokeDetailListByOrderIdResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetRevokeDetailListByOrderId", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetRevokeDetailListByOrderId")
    @ResponseWrapper(localName = "GetRevokeDetailListByOrderIdResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetRevokeDetailListByOrderIdResponse")
    @WebMethod(operationName = "GetRevokeDetailListByOrderId", action = "http://360buy.com/GetRevokeDetailListByOrderId")
    public com.jd.iwmss.stock.client.ArrayOfStockDetail getRevokeDetailListByOrderId(
        @WebParam(name = "intOrderId", targetNamespace = "http://360buy.com/")
        long intOrderId
    );

    @WebResult(name = "GetStocksHisResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetStocksHis", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStocksHis")
    @ResponseWrapper(localName = "GetStocksHisResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStocksHisResponse")
    @WebMethod(operationName = "GetStocksHis", action = "http://360buy.com/GetStocksHis")
    public com.jd.iwmss.stock.client.ArrayOfStock getStocksHis(
        @WebParam(name = "stock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.StockParamter stock
    );

    @WebResult(name = "GetRevokeKdanhaoByOrderResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetRevokeKdanhaoByOrder", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetRevokeKdanhaoByOrder")
    @ResponseWrapper(localName = "GetRevokeKdanhaoByOrderResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetRevokeKdanhaoByOrderResponse")
    @WebMethod(operationName = "GetRevokeKdanhaoByOrder", action = "http://360buy.com/GetRevokeKdanhaoByOrder")
    public com.jd.iwmss.stock.client.ArrayOfInt getRevokeKdanhaoByOrder(
        @WebParam(name = "OrderId", targetNamespace = "http://360buy.com/")
        long orderId
    );

    @WebResult(name = "CheckTransferStatusIsRejectedBySparePartsResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "CheckTransferStatusIsRejectedBySpareParts", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.CheckTransferStatusIsRejectedBySpareParts")
    @ResponseWrapper(localName = "CheckTransferStatusIsRejectedBySparePartsResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.CheckTransferStatusIsRejectedBySparePartsResponse")
    @WebMethod(operationName = "CheckTransferStatusIsRejectedBySpareParts", action = "http://360buy.com/CheckTransferStatusIsRejectedBySpareParts")
    public boolean checkTransferStatusIsRejectedBySpareParts(
        @WebParam(name = "expno", targetNamespace = "http://360buy.com/")
        java.lang.String expno
    );

    @WebResult(name = "GetOrderMonitorStockNumResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetOrderMonitorStockNum", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetOrderMonitorStockNum")
    @ResponseWrapper(localName = "GetOrderMonitorStockNumResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetOrderMonitorStockNumResponse")
    @WebMethod(operationName = "GetOrderMonitorStockNum", action = "http://360buy.com/GetOrderMonitorStockNum")
    public com.jd.iwmss.stock.client.ArrayOfOrderMonitor getOrderMonitorStockNum(
        @WebParam(name = "SkuId", targetNamespace = "http://360buy.com/")
        int skuId,
        @WebParam(name = "DepId", targetNamespace = "http://360buy.com/")
        int depId
    );

    @WebResult(name = "GetStockKdanhaoResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetStockKdanhao", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockKdanhao")
    @ResponseWrapper(localName = "GetStockKdanhaoResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockKdanhaoResponse")
    @WebMethod(operationName = "GetStockKdanhao", action = "http://360buy.com/GetStockKdanhao")
    public int getStockKdanhao(
        @WebParam(name = "stock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock stock
    );

    @WebResult(name = "UpdateStockResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "UpdateStock", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.UpdateStock")
    @ResponseWrapper(localName = "UpdateStockResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.UpdateStockResponse")
    @WebMethod(operationName = "UpdateStock", action = "http://360buy.com/UpdateStock")
    public int updateStock(
        @WebParam(name = "stock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock stock
    );

    @WebResult(name = "InsertStockGiftCardResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "InsertStockGiftCard", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.InsertStockGiftCard")
    @ResponseWrapper(localName = "InsertStockGiftCardResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.InsertStockGiftCardResponse")
    @WebMethod(operationName = "InsertStockGiftCard", action = "http://360buy.com/InsertStockGiftCard")
    public int insertStockGiftCard(
        @WebParam(name = "s1", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock s1,
        @WebParam(name = "s2", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock s2
    );

    @WebResult(name = "UpdateStockByCgdanhaoResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "UpdateStockByCgdanhao", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.UpdateStockByCgdanhao")
    @ResponseWrapper(localName = "UpdateStockByCgdanhaoResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.UpdateStockByCgdanhaoResponse")
    @WebMethod(operationName = "UpdateStockByCgdanhao", action = "http://360buy.com/UpdateStockByCgdanhao")
    public int updateStockByCgdanhao(
        @WebParam(name = "Cgdanhao", targetNamespace = "http://360buy.com/")
        int cgdanhao,
        @WebParam(name = "Cdanhao", targetNamespace = "http://360buy.com/")
        int cdanhao
    );

    @WebResult(name = "UpdateForQianZi3Result", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "UpdateForQianZi3", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.UpdateForQianZi3")
    @ResponseWrapper(localName = "UpdateForQianZi3Response", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.UpdateForQianZi3Response")
    @WebMethod(operationName = "UpdateForQianZi3", action = "http://360buy.com/UpdateForQianZi3")
    public int updateForQianZi3(
        @WebParam(name = "yuandanhao", targetNamespace = "http://360buy.com/")
        java.lang.String yuandanhao
    );

    @WebResult(name = "InsertVendorLossResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "InsertVendorLoss", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.InsertVendorLoss")
    @ResponseWrapper(localName = "InsertVendorLossResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.InsertVendorLossResponse")
    @WebMethod(operationName = "InsertVendorLoss", action = "http://360buy.com/InsertVendorLoss")
    public int insertVendorLoss(
        @WebParam(name = "inStock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock inStock,
        @WebParam(name = "outStock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock outStock
    );

    @WebResult(name = "WriteOffByKdanhaoResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "WriteOffByKdanhao", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.WriteOffByKdanhao")
    @ResponseWrapper(localName = "WriteOffByKdanhaoResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.WriteOffByKdanhaoResponse")
    @WebMethod(operationName = "WriteOffByKdanhao", action = "http://360buy.com/WriteOffByKdanhao")
    public int writeOffByKdanhao(
        @WebParam(name = "ErrorStock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock errorStock,
        @WebParam(name = "IsRevise", targetNamespace = "http://360buy.com/")
        boolean isRevise
    );

    @WebResult(name = "GetStockKdanhaoHisResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetStockKdanhaoHis", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockKdanhaoHis")
    @ResponseWrapper(localName = "GetStockKdanhaoHisResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockKdanhaoHisResponse")
    @WebMethod(operationName = "GetStockKdanhaoHis", action = "http://360buy.com/GetStockKdanhaoHis")
    public int getStockKdanhaoHis(
        @WebParam(name = "stock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock stock
    );

    @WebResult(name = "GetCgNumByCgDanhaoResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetCgNumByCgDanhao", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetCgNumByCgDanhao")
    @ResponseWrapper(localName = "GetCgNumByCgDanhaoResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetCgNumByCgDanhaoResponse")
    @WebMethod(operationName = "GetCgNumByCgDanhao", action = "http://360buy.com/GetCgNumByCgDanhao")
    public int getCgNumByCgDanhao(
        @WebParam(name = "SkuId", targetNamespace = "http://360buy.com/")
        int skuId,
        @WebParam(name = "DepId", targetNamespace = "http://360buy.com/")
        int depId,
        @WebParam(name = "intCgDanhao", targetNamespace = "http://360buy.com/")
        int intCgDanhao
    );

    @WebResult(name = "GetJigouIdByOrderIdResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetJigouIdByOrderId", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetJigouIdByOrderId")
    @ResponseWrapper(localName = "GetJigouIdByOrderIdResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetJigouIdByOrderIdResponse")
    @WebMethod(operationName = "GetJigouIdByOrderId", action = "http://360buy.com/GetJigouIdByOrderId")
    public int getJigouIdByOrderId(
        @WebParam(name = "intOrderId", targetNamespace = "http://360buy.com/")
        int intOrderId
    );

    @WebResult(name = "GetStockPanKuiSeResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetStockPanKuiSe", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockPanKuiSe")
    @ResponseWrapper(localName = "GetStockPanKuiSeResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockPanKuiSeResponse")
    @WebMethod(operationName = "GetStockPanKuiSe", action = "http://360buy.com/GetStockPanKuiSe")
    public com.jd.iwmss.stock.client.Stock getStockPanKuiSe(
        @WebParam(name = "pankuidanhao", targetNamespace = "http://360buy.com/")
        java.lang.String pankuidanhao,
        @WebParam(name = "orgid", targetNamespace = "http://360buy.com/")
        int orgid,
        @WebParam(name = "sid", targetNamespace = "http://360buy.com/")
        int sid
    );

    @WebResult(name = "updateSparePartsTransferStatusResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "updateSparePartsTransferStatus", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.UpdateSparePartsTransferStatus")
    @ResponseWrapper(localName = "updateSparePartsTransferStatusResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.UpdateSparePartsTransferStatusResponse")
    @WebMethod(action = "http://360buy.com/updateSparePartsTransferStatus")
    public int updateSparePartsTransferStatus(
        @WebParam(name = "expno", targetNamespace = "http://360buy.com/")
        java.lang.String expno,
        @WebParam(name = "status", targetNamespace = "http://360buy.com/")
        int status
    );

    @WebResult(name = "GetPOPKanhaoByOrderIdResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetPOPKanhaoByOrderId", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetPOPKanhaoByOrderId")
    @ResponseWrapper(localName = "GetPOPKanhaoByOrderIdResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetPOPKanhaoByOrderIdResponse")
    @WebMethod(operationName = "GetPOPKanhaoByOrderId", action = "http://360buy.com/GetPOPKanhaoByOrderId")
    public com.jd.iwmss.stock.client.ArrayOfInt getPOPKanhaoByOrderId(
        @WebParam(name = "OrderId", targetNamespace = "http://360buy.com/")
        long orderId,
        @WebParam(name = "Type", targetNamespace = "http://360buy.com/")
        int type
    );

    @WebResult(name = "IsReturnRepairResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "IsReturnRepair", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.IsReturnRepair")
    @ResponseWrapper(localName = "IsReturnRepairResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.IsReturnRepairResponse")
    @WebMethod(operationName = "IsReturnRepair", action = "http://360buy.com/IsReturnRepair")
    public int isReturnRepair(
        @WebParam(name = "OrderId", targetNamespace = "http://360buy.com/")
        long orderId,
        @WebParam(name = "SkuId", targetNamespace = "http://360buy.com/")
        int skuId
    );

    @WebResult(name = "GetKdanhaoByRfIdResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetKdanhaoByRfId", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetKdanhaoByRfId")
    @ResponseWrapper(localName = "GetKdanhaoByRfIdResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetKdanhaoByRfIdResponse")
    @WebMethod(operationName = "GetKdanhaoByRfId", action = "http://360buy.com/GetKdanhaoByRfId")
    public int getKdanhaoByRfId(
        @WebParam(name = "RfType", targetNamespace = "http://360buy.com/")
        int rfType,
        @WebParam(name = "RfId", targetNamespace = "http://360buy.com/")
        java.lang.String rfId
    );

    @WebResult(name = "GetStockResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetStock", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStock")
    @ResponseWrapper(localName = "GetStockResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockResponse")
    @WebMethod(operationName = "GetStock", action = "http://360buy.com/GetStock")
    public com.jd.iwmss.stock.client.Stock getStock(
        @WebParam(name = "kdanhao", targetNamespace = "http://360buy.com/")
        int kdanhao
    );

    @WebResult(name = "InsertStockRetunMoveResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "InsertStockRetunMove", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.InsertStockRetunMove")
    @ResponseWrapper(localName = "InsertStockRetunMoveResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.InsertStockRetunMoveResponse")
    @WebMethod(operationName = "InsertStockRetunMove", action = "http://360buy.com/InsertStockRetunMove")
    public int insertStockRetunMove(
        @WebParam(name = "retStock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock retStock,
        @WebParam(name = "outStock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock outStock
    );

    @WebResult(name = "GetStocksHisCountResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetStocksHisCount", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStocksHisCount")
    @ResponseWrapper(localName = "GetStocksHisCountResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStocksHisCountResponse")
    @WebMethod(operationName = "GetStocksHisCount", action = "http://360buy.com/GetStocksHisCount")
    public int getStocksHisCount(
        @WebParam(name = "stock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.StockParamter stock
    );

    @WebResult(name = "GetStockDetailsByKdanhaoResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetStockDetailsByKdanhao", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockDetailsByKdanhao")
    @ResponseWrapper(localName = "GetStockDetailsByKdanhaoResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockDetailsByKdanhaoResponse")
    @WebMethod(operationName = "GetStockDetailsByKdanhao", action = "http://360buy.com/GetStockDetailsByKdanhao")
    public com.jd.iwmss.stock.client.ArrayOfStockDetail getStockDetailsByKdanhao(
        @WebParam(name = "kdanhao", targetNamespace = "http://360buy.com/")
        int kdanhao
    );

    @WebResult(name = "InsertStockLogisticsLossResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "InsertStockLogisticsLoss", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.InsertStockLogisticsLoss")
    @ResponseWrapper(localName = "InsertStockLogisticsLossResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.InsertStockLogisticsLossResponse")
    @WebMethod(operationName = "InsertStockLogisticsLoss", action = "http://360buy.com/InsertStockLogisticsLoss")
    public int insertStockLogisticsLoss(
        @WebParam(name = "inStock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock inStock,
        @WebParam(name = "outStock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock outStock
    );

    @WebResult(name = "GetStockForOrderOutResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetStockForOrderOut", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockForOrderOut")
    @ResponseWrapper(localName = "GetStockForOrderOutResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockForOrderOutResponse")
    @WebMethod(operationName = "GetStockForOrderOut", action = "http://360buy.com/GetStockForOrderOut")
    public com.jd.iwmss.stock.client.ArrayOfStock getStockForOrderOut(
        @WebParam(name = "orderid", targetNamespace = "http://360buy.com/")
        long orderid
    );

    @WebResult(name = "UpdateStockByCdanhaoResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "UpdateStockByCdanhao", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.UpdateStockByCdanhao")
    @ResponseWrapper(localName = "UpdateStockByCdanhaoResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.UpdateStockByCdanhaoResponse")
    @WebMethod(operationName = "UpdateStockByCdanhao", action = "http://360buy.com/UpdateStockByCdanhao")
    public int updateStockByCdanhao(
        @WebParam(name = "Kdanhao", targetNamespace = "http://360buy.com/")
        int kdanhao,
        @WebParam(name = "Cdanhao", targetNamespace = "http://360buy.com/")
        int cdanhao,
        @WebParam(name = "Kuanx", targetNamespace = "http://360buy.com/")
        java.lang.String kuanx
    );

    @WebResult(name = "GetFullRevokeKdanhaoByOrderIdHisResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetFullRevokeKdanhaoByOrderIdHis", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetFullRevokeKdanhaoByOrderIdHis")
    @ResponseWrapper(localName = "GetFullRevokeKdanhaoByOrderIdHisResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetFullRevokeKdanhaoByOrderIdHisResponse")
    @WebMethod(operationName = "GetFullRevokeKdanhaoByOrderIdHis", action = "http://360buy.com/GetFullRevokeKdanhaoByOrderIdHis")
    public com.jd.iwmss.stock.client.ArrayOfInt getFullRevokeKdanhaoByOrderIdHis(
        @WebParam(name = "OrderID", targetNamespace = "http://360buy.com/")
        long orderID
    );

    @WebResult(name = "GetKdanhaoResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetKdanhao", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetKdanhao")
    @ResponseWrapper(localName = "GetKdanhaoResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetKdanhaoResponse")
    @WebMethod(operationName = "GetKdanhao", action = "http://360buy.com/GetKdanhao")
    public int getKdanhao(
        @WebParam(name = "stockParamter", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.StockParamter stockParamter
    );

    @WebResult(name = "GetCdanhaoByCgdanhaoResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetCdanhaoByCgdanhao", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetCdanhaoByCgdanhao")
    @ResponseWrapper(localName = "GetCdanhaoByCgdanhaoResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetCdanhaoByCgdanhaoResponse")
    @WebMethod(operationName = "GetCdanhaoByCgdanhao", action = "http://360buy.com/GetCdanhaoByCgdanhao")
    public int getCdanhaoByCgdanhao(
        @WebParam(name = "Cgdanhao", targetNamespace = "http://360buy.com/")
        int cgdanhao
    );

    @WebResult(name = "GetStockOfNPResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetStockOfNP", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockOfNP")
    @ResponseWrapper(localName = "GetStockOfNPResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStockOfNPResponse")
    @WebMethod(operationName = "GetStockOfNP", action = "http://360buy.com/GetStockOfNP")
    public com.jd.iwmss.stock.client.ArrayOfSkuStockNP getStockOfNP(
        @WebParam(name = "skuList", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.ArrayOfInt skuList
    );

    @WebResult(name = "UpdateForQianZiResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "UpdateForQianZi", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.UpdateForQianZi")
    @ResponseWrapper(localName = "UpdateForQianZiResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.UpdateForQianZiResponse")
    @WebMethod(operationName = "UpdateForQianZi", action = "http://360buy.com/UpdateForQianZi")
    public int updateForQianZi(
        @WebParam(name = "yuandanhao", targetNamespace = "http://360buy.com/")
        java.lang.String yuandanhao
    );

    @WebResult(name = "GetRevokeCountByOrderIdResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetRevokeCountByOrderId", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetRevokeCountByOrderId")
    @ResponseWrapper(localName = "GetRevokeCountByOrderIdResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetRevokeCountByOrderIdResponse")
    @WebMethod(operationName = "GetRevokeCountByOrderId", action = "http://360buy.com/GetRevokeCountByOrderId")
    public int getRevokeCountByOrderId(
        @WebParam(name = "OrderId", targetNamespace = "http://360buy.com/")
        long orderId
    );

    @WebResult(name = "GetInStockByCgdanhaoResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetInStockByCgdanhao", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetInStockByCgdanhao")
    @ResponseWrapper(localName = "GetInStockByCgdanhaoResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetInStockByCgdanhaoResponse")
    @WebMethod(operationName = "GetInStockByCgdanhao", action = "http://360buy.com/GetInStockByCgdanhao")
    public com.jd.iwmss.stock.client.ArrayOfStock getInStockByCgdanhao(
        @WebParam(name = "Cgdanhao", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.ArrayOfInt cgdanhao
    );

    @WebResult(name = "HasStockByRfIdResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "HasStockByRfId", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.HasStockByRfId")
    @ResponseWrapper(localName = "HasStockByRfIdResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.HasStockByRfIdResponse")
    @WebMethod(operationName = "HasStockByRfId", action = "http://360buy.com/HasStockByRfId")
    public boolean hasStockByRfId(
        @WebParam(name = "RfType", targetNamespace = "http://360buy.com/")
        int rfType,
        @WebParam(name = "RfId", targetNamespace = "http://360buy.com/")
        java.lang.String rfId
    );

    @WebResult(name = "GetFullRevokeKdanhaoByOrderIdResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetFullRevokeKdanhaoByOrderId", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetFullRevokeKdanhaoByOrderId")
    @ResponseWrapper(localName = "GetFullRevokeKdanhaoByOrderIdResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetFullRevokeKdanhaoByOrderIdResponse")
    @WebMethod(operationName = "GetFullRevokeKdanhaoByOrderId", action = "http://360buy.com/GetFullRevokeKdanhaoByOrderId")
    public com.jd.iwmss.stock.client.ArrayOfInt getFullRevokeKdanhaoByOrderId(
        @WebParam(name = "OrderID", targetNamespace = "http://360buy.com/")
        long orderID
    );

    @WebResult(name = "GetStocksCountResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetStocksCount", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStocksCount")
    @ResponseWrapper(localName = "GetStocksCountResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetStocksCountResponse")
    @WebMethod(operationName = "GetStocksCount", action = "http://360buy.com/GetStocksCount")
    public int getStocksCount(
        @WebParam(name = "stock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.StockParamter stock
    );

    @WebResult(name = "InsertStockFirmSendResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "InsertStockFirmSend", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.InsertStockFirmSend")
    @ResponseWrapper(localName = "InsertStockFirmSendResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.InsertStockFirmSendResponse")
    @WebMethod(operationName = "InsertStockFirmSend", action = "http://360buy.com/InsertStockFirmSend")
    public int insertStockFirmSend(
        @WebParam(name = "inStock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock inStock,
        @WebParam(name = "outStock", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.Stock outStock
    );

    @WebResult(name = "GetInStockTimeByCgdanhaoResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetInStockTimeByCgdanhao", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetInStockTimeByCgdanhao")
    @ResponseWrapper(localName = "GetInStockTimeByCgdanhaoResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetInStockTimeByCgdanhaoResponse")
    @WebMethod(operationName = "GetInStockTimeByCgdanhao", action = "http://360buy.com/GetInStockTimeByCgdanhao")
    public com.jd.iwmss.stock.client.ArrayOfStock getInStockTimeByCgdanhao(
        @WebParam(name = "Cgdanhao", targetNamespace = "http://360buy.com/")
        com.jd.iwmss.stock.client.ArrayOfInt cgdanhao
    );

    @WebResult(name = "GetCgZjineByCgDanhaoResult", targetNamespace = "http://360buy.com/")
    @RequestWrapper(localName = "GetCgZjineByCgDanhao", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetCgZjineByCgDanhao")
    @ResponseWrapper(localName = "GetCgZjineByCgDanhaoResponse", targetNamespace = "http://360buy.com/", className = "com.jd.iwmss.stock.client.GetCgZjineByCgDanhaoResponse")
    @WebMethod(operationName = "GetCgZjineByCgDanhao", action = "http://360buy.com/GetCgZjineByCgDanhao")
    public java.math.BigDecimal getCgZjineByCgDanhao(
        @WebParam(name = "intCgDanhao", targetNamespace = "http://360buy.com/")
        int intCgDanhao
    );
}
